### ISSUE TITLE
GraphQLDocumentError: Unknown type "__FRAGMENT_TYPE_NAME__"

### ISSUE THREAD

**Issue by nyvek28** [coreyward/gatsby-plugin-sanity-image#13]
Hi Corey,

Hope you're doing great. First of all, thank you for this amazing plugin! I've been looking for something like this for a while now :) Now, I keep getting an error that looks like this:

`GraphQLDocumentError: Unknown type "__FRAGMENT_TYPE_NAME__"`

My config looks like this:

```
{
    resolve: 'gatsby-plugin-sanity-image',
    options: {
      projectId: SANITY_PROJECT_ID,
      dataset: GATSBY_SANITY_DATASET,
      includeFragments: false
    }
}
```

Let's me run my dev environment with no issues but it does kill the build when I try to serve it. Not entirely sure why this is happening since I disabled the fragments, am I missing something? We are using typescript as well.

**Comment by coreyward** [comment]
Do you have a file at `.cache/fragments/gatsby-plugin-sanity-image.js`? If so, it's likely that you ran your dev server before setting `includeFragments` to `false`, which would have created that cached fragments file. Deleting it and restarting should fix the problem (or you can run `gatsby clean` from your project root if preferred).

If you don't have that file, or if removing it and restarting recreates it, or if doing so doesn't fix the problem, please provide details about the Gatsby version you're using and any other configuration info that might be related.

**Comment by nyvek28** [comment]
Hi @coreyward , thanks for the quick reply. So I just tested on a branch we have with Gatsby v3 and that seems to have solved the issue. Thank you! I'm closing the issue.

**Comment by timbakkum** [comment]
having the above issue on gatsby ^2.10.4. Is this plugin supposed to work with v2? because im also not seeing issues on a clean install with v3.

**Comment by coreyward** [comment]
@timbakkum Yep, it was developed against 2.x and is in active use with 2.x. Does running `gatsby clean` and restarting fix your issue?
