### ISSUE TITLE
Unknown type "SanityImageEntity" on gatsby v4 build 🤔

### ISSUE THREAD

**Issue by AaronBentley** [coreyward/gatsby-plugin-sanity-image#20]
I’m getting this error today when running Gatsby build, works fine when running Gatsby develop.
I’m using `gatsby@4.0.2`, `gatsby-source-sanity@7.1.0`& `gatsby-plugin-sanity-image@0.9.0`.
Here’s the error output when I run gatsby build:

```
 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Unknown type "SanityImageEntity". Did you mean "SanityImageFit", "SanityImageAsset", "SanityImage", "SanityImageCrop", or
"SanityImageHotspot"?

   1 | fragment ImageWithPreview on SanityImageEntity {
   2 |   ...Image
   3 |   asset {
   4 |     metadata {
   5 |       preview: lqip
   6 |     }
   7 |   }
   8 | }
   9 |
> 10 | fragment Image on SanityImageEntity {
     |                   ^
  11 |   asset {
  12 |     _id
  13 |   }
  14 |   hotspot {
  15 |     height
  16 |     width
  17 |     x
  18 |     y
  19 |   }
  20 |   crop {

File path: /Users/aaron/Apps/nosy/web/src/hooks/use-site-settings.js
Plugin: none
```

And here’s the contents of use-site-settings.js - note I’m getting the asset url, not …ImageWithPreview.

```
/**
 * Nosy SiteSettings Hook
 *
 * @export useSiteSettings
 */
import { graphql, useStaticQuery } from 'gatsby'

export const useSiteSettings = () => {
    const { siteSettings = {} } = useStaticQuery(
        graphql`
            query SITE_SETTINGS {
                siteSettings: sanitySiteSettings {
                    title
                    mainImage {
                        asset {
                            url
                        }
                    }
                }
            }
        `
    )

    return siteSettings
}

```

Any ideas on how to rectify this? (edited)

**Comment by coreyward** [comment]
Gatsby 4.0 [no longer supports modifying the schema from `sourceNodes`](https://v4.gatsbyjs.com/docs/reference/release-notes/migrating-from-v3-to-v4/#disallow-schema-related-apis-in-sourcenodes), which prevents `gatsby-plugin-sanity-image@0.9.0` from working.  Can you try updating to `0.10.0-alpha.0` to see if switching from `sourceNodes` to `createSchemaCustomization` resolves this?

**Comment by AaronBentley** [comment]
Thank you @coreyward, I can confirm the site now builds as intended 🥳
Sincere thank you from myself & the team for your swift reply and resolution - have a nice day 😃

**Comment by ajmalafif** [comment]
Hi @AaronBentley great to see you manage to get it to work! Do you mind sharing if your `customImageTypes` for your config in `gatsby-config.js` because I am still getting error message with `0.10.0`. 

How I isolate this as <SanityImage/> related is because I have a branch with <GatsbyImage/> and it compiles okay.
I keep getting these errors: 

```
 WebpackError: TypeError: Cannot read property 'metadata' of undefined
 ```

**Comment by AaronBentley** [comment]
Hey @ajmalafif, sure! Here's what I've got...

First up, here's the "Main Image' schema I use for Sanity:

```javascript
export default {
    title: 'Image',
    name: 'mainImage',
    type: 'image',
    options: {
        hotspot: true
    },
    fields: [
        {
            name: 'caption',
            type: 'string',
            title: 'Caption',
            options: {
                isHighlighted: true
            }
        },
        {
            name: 'alt',
            type: 'string',
            title: 'Alternative text',
            description: 'Important for SEO and accessiblity.',
            options: {
                isHighlighted: true
            }
        }
    ]
}
``` 

Next up, here's the `gatsby-config.js` plugins entry for `gatsby-plugin-sanity-image`:

```javascript
// In the gatsby-config plugins array...
...
{
  resolve: 'gatsby-plugin-sanity-image',
  options: {
      projectId: process.env.GATSBY_SANITY_PROJECT_ID,
      dataset: process.env.GATSBY_SANITY_DATASET,
      // Provide the custom image type name used in Sanity data schema above
      customImageTypes: ['SanityMainImage'],
      defaultImageConfig: {
          quality: 75,
          fit: 'max',
          auto: 'format'
      }
  }
},
```

Then you should be able to query the image data in GraphQL like so:

```graphql
mainImage {
    ...ImageWithPreview
    alt
}
```

Hope this helps my friend, let me know if you need anything else 🥳

**Comment by ajmalafif** [comment]
thank you @AaronBentley !

**Comment by coreyward** [comment]
@AaronBentley As of v0.9.0+ you can move the `alt` field into the fragment using the `customFields` configuration option. E.g.: 

```js
{
  resolve: 'gatsby-plugin-sanity-image',
  options: {
    projectId: process.env.SANITY_PROJECT_ID,
    dataset: process.env.SANITY_DATASET,

    // Include alt field on image interface
    customFields: [{ name: "alt", type: "String" }],
  },
}
```

This would mean your alt field is always retrieved when you use either `...Image` or `...ImageWithPreview`. 

Cheers!
