### ISSUE TITLE
Unknown fragment "ImageWithPreview"

### ISSUE THREAD

**Issue by mister-cairns** [coreyward/gatsby-plugin-sanity-image#22]
I have a fresh install of Gatsby 4.4.0 and 0.11.0 of this plugin. It won't allow to not include `gatsby-plugin-image` (build fails without it) and I am unable to get any of the Sanity Image data from graphql. 

Gatsby config is as follows:

```
  plugins: [
    {
      resolve: "gatsby-source-sanity",
      options: {
        ...clientConfig.sanity,
      },
    },
    {
      resolve: "gatsby-plugin-sanity-image",
      options: {
        ...clientConfig.sanity,
        customImageTypes: ["SanityDefaultImage"],
      },
    },
    "gatsby-plugin-image",
    "gatsby-plugin-sharp",
    "gatsby-transformer-sharp",
    "gatsby-plugin-react-helmet",
    "gatsby-plugin-sitemap",
    "gatsby-plugin-postcss",
  ],
```

I get these warnings in the gatsby build"

```
warn Plugin `gatsby-plugin-sanity-image` has customized the GraphQL
type `SanityImage`, which has already been defined by the plugin
`gatsby-source-sanity`. This could potentially cause conflicts.
warn Plugin `gatsby-plugin-sanity-image` has customized the GraphQL
type `SanityDefaultImage`, which has already been defined by the plugin
 `gatsby-source-sanity`. This could potentially cause conflicts.
```

And here's the graphql output:
<img width="1031" alt="CleanShot 2021-12-27 at 10 31 04@2x" src="https://user-images.githubusercontent.com/1581854/147422451-3b9bbde4-3869-4457-a99f-b943e5b90c40.png">

Any ideas would be greatly appreciated.

**Comment by coreyward** [comment]
Could be a number of things. Is the fragment working anywhere else? If not, you may just need to clear the cache and reboot to get Gatsby to pick up the new fragments. If so, perhaps the GraphQL type of your `image` field on the `SanityContentImage` type might not be `SanityDefaultImage` or `SanityImage`. 

For what it's worth, [the warnings are expected](https://github.com/coreyward/gatsby-plugin-sanity-image/wiki/Custom-Sanity-Image-Types) and the dependency on `gatsby-plugin-image` is actually from `gatsby-source-sanity`, not `gatsby-plugin-sanity-image`. I too wish they'd drop it, but you'll have to bring it up with the Sanity team.

**Comment by mister-cairns** [comment]
Thanks, @coreyward — I switched back to the default image type, ran `gatsby clean`, and it's back up and running.

Good to know re. The warnings, too.
