### ISSUE TITLE
`fadeIn` does not work

### ISSUE THREAD

**Issue by Brydom** [coreyward/gatsby-plugin-sanity-image#23]
Hey! I'm trying to get the `fadeIn` prop working and I'm having some issues. I'm unsure if there's actual support for this in this plugin, but it doesn't seem to be working whatever I try.

- Adding `fadeIn: true` to the `config` object:
```
Error in function eval in ./node_modules/gatsby-plugin-sanity-image/index.js:226
acc[key] is not a function
```
- Adding `fadeIn` to the component, no behaviour change
- Adding `fadeIn: true` to the `options` object, no behaviour change

Reference: https://www.gatsbyjs.com/plugins/gatsby-image/#gatsby-image-props

**Comment by coreyward** [comment]
This plugin is not Gatsby Image. See the README for info on the difference and why this is a better approach for a majority of Sanity users.

**Comment by Brydom** [comment]
Is there a way to transition out of the blurry image in this plugin? That is the goal of this issue

**Comment by coreyward** [comment]
There is not currently any built-in blur-up behavior, but if you opt not to provide a preview image you get a single `img` tag out, so you could build your own blur-up component with two separate `img` tags starting with the existing `ImageWithPreview` component:

https://github.com/coreyward/gatsby-plugin-sanity-image/blob/fd421c5050827aeb885c0c8d0b13e3703bf2bef4/src/index.jsx#L207-L256
