### ISSUE TITLE
Image Stuck On Blurred Placeholder

### ISSUE THREAD

**Issue by 3200pro** [coreyward/gatsby-plugin-sanity-image#26]
Hi Cory,

 I'm having a problem that has to do with `postion: absolute` being added to a parent container. It causes the image to be stuck in the blurry placeholder position. It only seems to be on the initial load of the page. Secondary loads the image works fine.

(Here's my setup.)

```
...
const bgImage = data.bgImage?.image 
...
<div className="absolute inset-0">
          <Image
            {...bgImage}
            width={400}
            alt={bgAlt}
            className={'h-full w-full object-cover'}
          />
        </div> ..
```

Removing `absolute` fixes it in my testing. Refreshing a page also loads the image. Is there something I'm missing? Thanks!

![Screen Shot 2022-04-12 at 8 59 44 AM](https://user-images.githubusercontent.com/68202671/162980453-81364871-0dca-4739-a700-2a9b1f871b2b.jpg)

**Comment by coreyward** [comment]
This is typically a pretty easy fix that is documented in the README. I go into more detail here: https://github.com/coreyward/gatsby-plugin-sanity-image/issues/15#issuecomment-891123058

**Comment by 3200pro** [comment]
That's an interesting problem I haven't encountered. Kind of a sneaky one.

In my case,  `overflow: hidden` was the culprit.  Your mention of it in https://github.com/coreyward/gatsby-plugin-sanity-image/issues/15#issuecomment-891123058 saved the day. Thanks for the promptness on an answer as well
