### ISSUE TITLE
Option for disabling loading="lazy"

### ISSUE THREAD

**Issue by simonandywilson** [coreyward/gatsby-plugin-sanity-image#27]
It would be great if there was an option to disable the `loading="lazy"` attribute that is added to the image tag (or to change the attribute to "eager").

When an image is above the fold, the "lazy" attribute increases Largest Contentful Paint notably (in my case by 40%).

**Comment by coreyward** [comment]
Since the props you pass are expanded after `loading="lazy"` you can simply pass your own `loading` prop to override. E.g.:

```
<SanityImage {...image} loading="eager" />
```
