### ISSUE TITLE
Fragment "Image" is never used.

### ISSUE THREAD

**Issue by bzmillerboy** [coreyward/gatsby-plugin-sanity-image#34]
I moved a query from a `useStaticQuery` to the page query and I'm now getting the following error.

```
Fragment "Image" is never used.

GraphQL request:2:7
1 |
2 |       fragment Image on SanityImageEntity {
  |       ^
3 |         asset {
```
<img width="624" alt="Screen Shot 2022-11-21 at 4 30 26 PM" src="https://user-images.githubusercontent.com/1130899/203162329-8d70d950-aa68-4a92-909b-6b613770fb79.png">

Versions:
"gatsby": "^5.0.1",
"gatsby-plugin-sanity-image": "^0.13.2",

**Comment by coreyward** [comment]
Are you defining the fragment in `src/templates/rentals.js`? If so, it would be useful to hear more about what your thinking is / what you are expecting so I can help.

**Comment by bzmillerboy** [comment]
I've tried defining the fragment in my template query but I then get this error.

`The fragment "ImageWithPreview" does not exist.`

```
    {
      page: allSanityPage {
        edges {
          node {
            id
            mainImage {
              ...ImageWithPreview
            }
            slug {
              current
            }
          }
        }
      }
    fragment Image on SanityMainImage {
      hotspot {
        height
        width
        x
        y
      }
      crop {
        bottom
        left
        right
        top
      }
      asset {
        _id
      }
    }
    fragment ImageWithPreview on SanityMainImage {
      ...Image
      asset {
        metadata {
          preview: lqip
        }
      }
    }
```

If I move this query to gatsby-node.js it runs fine, it's only when it exist inside my page template. I don't typically have to import or define the fragment and I use it all over my app (in different pages and components).

I'm expecting to use the `...ImageWithPreview` fragment in my query then use that data in a `<SanityImage {...mainImage} />` component.

**Comment by bzmillerboy** [comment]
There seems to be something unique about this component, it appears to only fail in `rentals.js`.

Doesn't work in rentals.js but does in blog-post.js:
<img width="1966" alt="Screen Shot 2022-11-26 at 11 46 24 AM" src="https://user-images.githubusercontent.com/1130899/204099621-d2ed684a-2b61-460a-9805-6338ef56ab89.png">


Works:
<img width="1995" alt="Screen Shot 2022-11-26 at 11 45 59 AM" src="https://user-images.githubusercontent.com/1130899/204099612-69075ddf-d62c-4f39-b767-490756dad255.png">

**Comment by coreyward** [comment]
You shouldn’t need to define the fragment (i.e., `fragment Image on SomeImageType { ... }`) anywhere in your code when you're using gatsby-plugin-sanity-image.

This might seem out of the blue, but are you reusing the query name `PageTemplateQuery` anywhere else? If so, and that query isn't using the `Image` fragment, that might be the source of this error.

**Comment by bzmillerboy** [comment]
You nailed it. It was a duplicate query name. And yes, the other page template containing the duplicate query name doesn't make use of any fragments.

Thanks for debugging for me. Sorry to bother given it wasn't a `gatsby-plugin-sanity-image` issue but rather a red herring appearing to blame SanityImage. I appreciate it!
