### ISSUE TITLE
Request: functionality to use as background-image

### ISSUE THREAD

**Issue by dieterwalckiers** [coreyward/gatsby-plugin-sanity-image#37]
It would be great if we could use this as a background image instead of outputting an `<img>` tag.
Perhaps a React hook that produces the `src` attribute?

**Comment by coreyward** [comment]
I typically don‘t use CSS background images in React websites. While CSS was quicker to provide the means to provide DPI-responsive images, the capabilities of the `img` element with `srcset` and `sizes` results in more performant pages (browsers can choose the right image based on viewport size and eager load it before the initial paint and before CSS is even parsed). Images this way can also include `alt` text for accessibility, or explicitly marked as stylistic via `alt=""`.

Here's an example of how to use gatsby-plugin-sanity-image to render an image in the background of a hero component using Emotion’s `css` prop for css-in-js:

```jsx
import React from "react"
import SanityImage from "gatsby-plugin-sanity-image"

const Hero = ({ title, image }) => (
  <section css={{ position: "relative", paddingBlock: 50, paddingInline: 30 }}>
    <SanityImage
      {...image}
      width={1440}
      sizes="100vw"
      alt=""
      css={{
        position: "absolute",
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        objectFit: "cover", // SanityImage will use the hotspot to set the `object-position`, if it exists
      }}
    />

    <h1 css={{ position: "relative", zIndex: 2 }}>{title}</h1>
  </section>
)

export default Hero
```

**Comment by dieterwalckiers** [comment]
Thanks a lot for the info! I'm confident I'll be able to make it work in my use case (an image with parallax effect).
