### ISSUE TITLE
TypeScript: `img` attribute types missing

### ISSUE THREAD

**Issue by jfgilmore** [coreyward/gatsby-plugin-sanity-image#38]
It seems the generated TypeScript types no longer include `crossorigin`, `decoding`, `elementtiming`, `fetchpriority`, `ismap`, `loading`, `referrerpolicy`, `role`, `srcset`, and `usemap`, as of `v0.13.3`

It's true that the previous type definitions were too permissive however this may be a source of frustration. Let me know if you would like assistance.

Current workaround: use `v0.13.2`

**Comment by coreyward** [comment]
Ugh, that's disappointing. Thanks for the report.

Do you know if there is an easy way for `SanityImage` to extend the default `img` element props in JSDoc to resolve this?

**Comment by coreyward** [comment]
@jfgilmore Are you still available to assist on this?

**Comment by jfgilmore** [comment]
> @jfgilmore Are you still available to assist on this?
The earliest I can get to it is probably next week.

**Comment by jfgilmore** [comment]
I have submitted #41 which hopefully resolves this. I have omitted `fetchpriority` due to it's experimental status and `ismap` as its use is not recommended (it's also not included in the default props for `img` elements in React).

**Comment by coreyward** [comment]
Fixed in #41 (v0.13.4).
