### ISSUE TITLE
localFile

### ISSUE THREAD

**Issue by pierrenel** [coreyward/gatsby-plugin-sanity-image#44]
Is there a way to ... use the local file (in /static) vs fetching it off the Sanity CDN on each page load? My traffic quota is over a bazillion :(

**Comment by coreyward** [comment]
The Sanity Image API does both the transformations and serving via CDN. This library really just orchestrates, generating URLs and wrapping them up into the relevant JSX/markup. As such, approaches that involve fetching all of the variants that could possibly be on every build, or fetching the originals and creating all of the versions needed using sharp during the build process are out of scope. For reference, the deprecated gatsby-image plugin handled much of this, but even Gatsby moved beyond these foot-guns.

My two cents: the bandwidth has to come from somewhere, and being generally conscious about file sizes and formats is sufficient to keep usage down. Even on very popular, media-rich websites I have worked on in the past, images are really not too expensive. At $0.20/GB on the free plan, a typical “large” 250KB image can be downloaded 4,000 times before hitting 1GB, or $0.00005 per download, with on-the-fly generation and serving from the Google CDN included. Those prices drop on higher plans, too.

If you were so inclined to reduce costs from here, though, you could look at combining providers, adding CloudFlare in the mix in a way that proxies your image requests to Sanity, removing the bandwidth costs from the equation and focusing instead on CPU-time or invocation count as the billable metric. If you do go this route, you'll need to provide a custom URL to gatsby-plugin-sanity-image via the `baseUrl` config option.

Good luck!
