### ISSUE TITLE
Request: Alternative prop name for 'width'

### ISSUE THREAD

**Issue by kupe517** [coreyward/gatsby-plugin-sanity-image#45]
Would it be possible to create an additional prop name to help set the width of the image? The reason I ask is that I use this in combo with Chakra-UI and the `width` prop conflicts with their props. For example the following code will not size the image correctly:

```
<Box
  as={SanityImage}
  {...image}
  alt={image?.asset?.altText}
  hotspot={image.hotspot}
  crop={image.crop}
  width={600}
/>
```

It would however work if the prop was something like `assetWidth`.

Thanks!

**Comment by coreyward** [comment]
This would be a breaking change that I would very much prefer to avoid, but I found this potential workaround: https://github.com/chakra-ui/chakra-ui/issues/5489

Alternately, you can try inverting these to something like `<SanityImage as={Box} … />` and see if that works for you.

If that doesn’t work, though, I would suggest opening a ticket with Chakra if you’re looking to keep a Chakra component from consuming a prop you are using for a custom component.
